### PR TITLE
CLI, Dockerfile, new listitems method, changed upload method

### PR DESCRIPTION
**Pull request by soulshake**
This PR:
- Adds a CLI (using click): `nc.py`,
- modifies the `upload` method to be a bit more standard (should accept arguments as source-target rather than target-source),
- adds a `Dockerfile` so it can be run in a container,
- add a new method `listitems`,
- improves usefulness of Exception messages

Additional dependencies: `click` and `tabulate`.

### CODE REVIEW

**Comment by ghost** [comment]
You may want to rename the script - nc is a well known Unix tool.

**Comment by soulshake** [comment]
@voltagex `nc` is only used as a variable name ([in `neocli.py`](https://github.com/soulshake/python-neocities/blob/master/neocities/neocli.py#L83)).
The Docker entrypoint _was_ `nc.py`, but was then [changed](https://github.com/soulshake/python-neocities/commit/5bc6b2b3e11c3f873df586bdaf991d208522e16f) to `neocities`.

Correct me if I missed something, but I can't think of a case where that would cause a conflict here.

**Comment by ghost** [comment]
Right yep, sorry. Missed that. Is the Dockerfile included in this pull?

**Comment by soulshake** [comment]
[Yes](https://github.com/neocities/python-neocities/pull/1/files).

**Comment by kyledrake** [comment]
I kindof forked this from the original and didn't think of the implications of that!

I can do two things here:

1) Delete this repo and point everyone to your repo
2) Give you admin on this repo and you can do whatever you want with it.

What works best for you @soulshake?

Thanks for this BTW!

**Comment by kyledrake** [comment]
Edit: oh weird, this is the origination repo. I'm confused now...
Contrib access coming your way :)

I'm :+1: to whatever you want to do here.

**Pull request merged**
